### ISSUE TITLE
Maven group id and package

### ISSUE THREAD

**Issue by dussab** [jclagache/spring-data-mybatis#1]
Hi Jean-Christophe,
Your project looks quite interesting and I'm sure MyBatis and Spring users will be excited to see such a community project. One area that will be confusing for users as well as cause problems if you ever decide to publish the project to Maven central is the use of the use of the org.springframework\* group id and package structure. We reserve org.springframework\* group id for Spring projects that are maintained or directly endorsed (usually as part of a release train) by the Spring engineering team. I'd ask that you change the group id and package naming to reflect your domain versus the spring domain. 

Thanks,
Brian

**Comment by jclagache** [comment]
Hi Brian,
first of all, sorry for taking so long to respond.
Thank your for paying attention to this project. Its goal never was to publish it on Maven central or other public Maven repo as a library dependency but more an exercice for a Spring framework deeper usage.
However, I agree with your observation, thank your for it and make the corresponding changes asap.
Jean-Christophe

**Comment by dussab** [comment]
No problem and I appreciate the consideration and resolution. 

Thanks,
Brian
